### ISSUE TITLE
[Android] Missing interpolation type

### ISSUE THREAD

**Issue by Choyeongdeok** [arshigtx/react-native-custom-switch#5]
![스크린샷 2023-01-25 오후 4 28 17](https://user-images.githubusercontent.com/54658590/214504445-b93ffbf3-00d4-42d1-9542-90f76da8f587.png)

I got an error when I pressed CustomSwitch component in android.

react: 18.0.0
react-native: 0.69.1
react-native-custom-switch: 1.0.7

**Comment by adexp01** [comment]
@Choyeongdeok  In file CustomSwitch just change
from 
`const layoutAnim = {
    Opacity: () =>
      LayoutAnimation.configureNext(
        LayoutAnimation.create(
          animationSpeed ? animationSpeed : defaultValues.animationSpeed,
          LayoutAnimation.Types.Spring,
          LayoutAnimation.Properties.opacity,
        ),
      ),
  };
`
to

`const layoutAnim = {
    Opacity: () =>
      LayoutAnimation.configureNext(
        LayoutAnimation.create(
          animationSpeed ? animationSpeed : defaultValues.animationSpeed,
          LayoutAnimation.Types.easeInEaseOut,
          LayoutAnimation.Properties.opacity,
        ),
      ),
  };`

**Comment by Choyeongdeok** [comment]
@adexp01 thx, but I used https://www.npmjs.com/package/react-native-custom-switch-new instead of this.
